name: cabal-3.2
on:
  pull_request:
  push:
jobs:
  cabal:
    name: ${{ matrix.os }} / ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.2"]
        ghc: ["8.8.4"]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Build
        run: bash bug.sh
